os:
  - linux
  - osx

env:
  - VERSION=3.5.7.2
  - VERSION=3.6.7.2
  - VERSION=4.0.6.2
  - VERSION=4.1.6.1
  - VERSION=4.2.8.2
  - VERSION=4.3.7.2
  - VERSION=4.4.7.2
  - VERSION=5.0.5.2
  - VERSION=5.1.1.3
  - VERSION=5.1.2.1

matrix:
  allow_failures:
    - os: osx
    - os: linux
    - env: VERSION=5.1.2.1
  exclude:
    - os: osx
      env: VERSION=3.5.7.2

before_install:
  - sudo VERSION=$VERSION bash ci/linux.bash
  - sudo VERSION=$VERSION bash ci/osx.bash

script:
  - make -C tests
